import styles from "@/app/ui/app/home.module.css";
import "@/app/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "./context/auth/authContext";
import Footer from "./ui/app/footer/footer";
import Header from "./ui/app/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          <AuthContextProvider>
            <Header />
            <div className={styles.content}>{children}</div>
            <Footer />
          </AuthContextProvider>
        </div>
      </body>
    </html>
  );
}
